apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: greetings-from-world-and-space
spec:
  params:
  - name: username
    type: string
  tasks:
    - name: hello-goodbye
      pipelineref:
        name: hello-goodbye
    - name: hello-goodbye-space
      runAfter:
        - hello-goodbye
      taskRef:
        name: hello-goodbye-space
      params:
      - name: username
        value: $(params.username)